name: shopsync
description: "ShopSync - Share shopping lists with family and friends"
publish_to: "none"

version: 3.5.0

environment:
  sdk: ^3.6.0

dependencies:
  sentry_flutter: ^8.14.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  #  google_sign_in: ^6.2.2
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  in_app_update: ^4.2.3
  intl: 0.20.2
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  path_provider: ^2.0.15
  share_plus: ^7.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geocoding: ^2.2.0
  lucide_icons_flutter: ^3.0.5
  m3e_collection: ^0.3.7
  web: ^1.1.1
  flutter_staggered_animations: ^1.1.1
  google_sign_in: ^6.3.0
  flutter_svg: ^2.1.0
  amplitude_flutter: ^4.0.0
  google_mobile_ads: ^6.0.0
  flutter_inappwebview: ^6.1.5
  lottie: ^3.1.2
  connectivity_plus: ^5.0.2
  home_widget: ^0.6.0
  flutter_expandable_fab: ^2.3.0
  tflite_flutter: ^0.11.0
  collection: ^1.18.0

dev_dependencies:
  sentry_dart_plugin: ^2.4.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logos/
    - assets/badges/google/android/png@4x/dark/android_dark_rd_na@4x.png
    - assets/badges/google/android/png@4x/light/android_light_rd_na@4x.png
    - assets/badges/google/web/png@4x/dark/web_dark_rd_na@4x.png
    - assets/badges/google/web/png@4x/light/web_light_rd_na@4x.png
    - assets/icons/food_icons/bakery/
    - assets/icons/food_icons/berries/
    - assets/icons/food_icons/desserts/
    - assets/icons/food_icons/dishes/
    - assets/icons/food_icons/drinks/
    - assets/icons/food_icons/fastfood/
    - assets/icons/food_icons/fruits/
    - assets/icons/food_icons/ingredients/
    - assets/icons/food_icons/kawaii/
    - assets/icons/food_icons/meat/
    - assets/icons/food_icons/nutrition/
    - assets/icons/food_icons/nuts/
    - assets/icons/food_icons/pastries/
    - assets/icons/food_icons/seafood/
    - assets/icons/food_icons/vegetables/
    - assets/icons/food_icons/other/
    - assets/animations/no_internet.json

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: shopsync
  org: aadishsdev
